source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'bcrypt-ruby'
gem 'faker'


gem 'jquery-rails'

group :development, :test do
  gem 'rspec-rails'
  gem 'shoulda-matchersg'
end
