source 'https://rubygems.org'

gem 'rails', '3.2.13'

gem 'pg'

group :assets do

  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'rspec-rails'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'sextant'
  gem 'rails_db_info'
end

group :test do
  gem 'shoulda-matchers'
  gem 'shoulda-matchers-callbacks'
end

gem 'jquery-rails'

gem 'debugger'
